# Semana 4 — Taller práctico: funciones, modularización y GitHub

**Asignatura:** Análisis de Datos con Python  
**Tipo de evidencia:** Notebook con ejercicios resueltos + repositorio inicial en GitHub  

## Propósito del taller

Aplicar funciones, modularización básica, comprensión de listas y diccionarios, manejo de errores y buenas prácticas de programación en un caso sencillo de análisis de datos.

## Entregables

1. Notebook completo con los ejercicios resueltos.
2. Repositorio inicial en GitHub con estructura organizada.
3. Archivo `README.md` con descripción del repositorio.
4. Evidencia del enlace al repositorio en la última sección del notebook.

## Instrucciones

Complete las celdas marcadas con `TODO`.

In [ ]:
# Cargue y observe aquí los datos.
from pathlib import Path
import pandas as pd
import numpy as np

df=pd.read_csv('/content/sample_data/mecatronics_dataset.csv')
df.head()

   time  temperature_C  vibration_g  current_A system_state
0     0      20.397371     0.709903   1.932482       normal
1     1      19.989382     0.638695   1.995546       normal
2     2      20.718098     0.508945   1.940743       normal
3     3      21.518244     0.402959   1.999154       normal
4     4      20.212251     0.604733   1.850520       normal

In [ ]:
df['voltaje'] = np.random.uniform(1, 20, size=len(df))
df.head()

   time  temperature_C  vibration_g  current_A system_state    voltaje
0     0      20.397371     0.709903   1.932482       normal   8.391851
1     1      19.989382     0.638695   1.995546       normal  18.845169
2     2      20.718098     0.508945   1.940743       normal  15.439083
3     3      21.518244     0.402959   1.999154       normal  14.100072
4     4      20.212251     0.604733   1.850520       normal   7.551159

In [ ]:
print("Dimensiones:", df.shape)

print("\nColumnas:")
print(df.columns.tolist())

print("\nTipos de datos:")
display(df.dtypes)

print("\nValores faltantes:")
display(df.isna().sum())

print("\nResumen general:")
display(df.describe(include="all"))

Dimensiones: (1000, 6)

Columnas:
['time', 'temperature_C', 'vibration_g', 'current_A', 'system_state', 'voltaje']

Tipos de datos:

time               int64
temperature_C    float64
vibration_g      float64
current_A        float64
system_state      object
voltaje          float64
dtype: object

Valores faltantes:

time             0
temperature_C    0
vibration_g      0
current_A        0
system_state     0
voltaje          0
dtype: int64

Resumen general:

,time,temperature_C,vibration_g,current_A,system_state,voltaje
count,1000.000000,1000.000000,1000.000000,1000.000000,1000,1000.000000
unique,NaN,NaN,NaN,NaN,2,NaN
top,NaN,NaN,NaN,NaN,normal,NaN
freq,NaN,NaN,NaN,NaN,988,NaN
mean,499.500000,20.161158,0.510625,2.012499,NaN,10.416923
std,288.819436,3.551832,0.149618,0.231031,NaN,5.533852
min,0.000000,13.056041,0.058942,1.446479,NaN,1.000677
25%,249.750000,16.763544,0.409064,1.816269,NaN,5.670154
50%,499.500000,20.458939,0.509462,2.024081,NaN,10.295870
75%,749.250000,23.433047,0.609332,2.208529,NaN,15.212482
max,999.000000,26.537331,0.978966,2.569301,NaN,19.984625

## Parte 1 — Función para convertir valores

Cree una función llamada `convertir_a_float(valor)` que intente convertir un valor a número decimal.

La función debe retornar:

- El número convertido, si la conversión es posible.
- `None`, si el valor no se puede convertir.

In [ ]:
# TODO: cree la función convertir_a_float

def convertir_a_float(valor):
  try:
    return float(valor)
  except:
    return None
    pass

# Pruebas sugeridas
print(convertir_a_float("12.5"))
print(convertir_a_float("error"))
print(convertir_a_float(""))
print(convertir_a_float(None))

12.5
None
None
None

## Parte 2 — Función para calcular potencia

Cree una función llamada `calcular_potencia(voltaje, corriente)`.

La función debe:

- Retornar `None` si voltaje o corriente son `None`.
- Retornar `None` si voltaje o corriente son negativos.
- Retornar `voltaje * corriente` en los demás casos.

In [ ]:
# TODO: cree la función calcular_potencia

def calcular_potencia(voltaje, corriente):
  if voltaje is None or corriente is None:
    return None
  elif voltaje <0 or corriente <0:
    return None
  else:
    return voltaje*corriente
    pass

# Pruebas sugeridas
print(calcular_potencia(12, 2))
print(calcular_potencia(None, 2))
print(calcular_potencia(12, -1))

24
None
None

## Parte 3 — Función para clasificar temperatura

Cree una función llamada `clasificar_temperatura(temp)` con los siguientes criterios:

- Si `temp` es `None`: `"Dato inválido"`
- Si `temp < 40`: `"Normal"`
- Si `40 <= temp < 50`: `"Precaución"`
- Si `temp >= 50`: `"Alerta"`

In [ ]:
# TODO: cree la función clasificar_temperatura

def clasificar_temperatura(temp):
  if temp is None:
    return "Dato invalido"
    pass
  elif temp <15:
    return "Normal"
  elif 15<=temp<24:
    return "Precaucion"
  elif temp>=24:
    return "Alerta"
    pass

# Pruebas sugeridas
print(clasificar_temperatura(35))
print(clasificar_temperatura(45))
print(clasificar_temperatura(52))
print(clasificar_temperatura(None))

Alerta
Alerta
Alerta
Dato invalido

## Parte 4 — Limpieza y procesamiento de registros

Procese la lista `registros_crudos` y cree una nueva lista llamada `registros_limpios`.

Cada registro limpio debe contener:

- `id`
- `voltaje`
- `corriente`
- `temperatura`
- `potencia`
- `estado_temperatura`

Use las funciones creadas.

In [ ]:
# TODO: procese los registros

registros_limpios=df.copy()

registros_limpios.drop_duplicates(inplace=True)

registros_limpios['current_A']=registros_limpios['current_A'].apply(convertir_a_float)
registros_limpios['voltaje']=registros_limpios['voltaje'].apply(convertir_a_float)
registros_limpios['temperature_C']=registros_limpios['temperature_C'].apply(convertir_a_float)
registros_limpios['vibration_g']=registros_limpios['vibration_g'].apply(convertir_a_float)
registros_limpios['time']=registros_limpios['time'].apply(convertir_a_float)

display(registros_limpios.head())
print("\nValores faltantes:")
display(df.isna().sum())
display(df.describe(include="all"))

   time  temperature_C  vibration_g  current_A system_state    voltaje
0   0.0      20.397371     0.709903   1.932482       normal   8.391851
1   1.0      19.989382     0.638695   1.995546       normal  18.845169
2   2.0      20.718098     0.508945   1.940743       normal  15.439083
3   3.0      21.518244     0.402959   1.999154       normal  14.100072
4   4.0      20.212251     0.604733   1.850520       normal   7.551159

Valores faltantes:

time             0
temperature_C    0
vibration_g      0
current_A        0
system_state     0
voltaje          0
dtype: int64

,time,temperature_C,vibration_g,current_A,system_state,voltaje
count,1000.000000,1000.000000,1000.000000,1000.000000,1000,1000.000000
unique,NaN,NaN,NaN,NaN,2,NaN
top,NaN,NaN,NaN,NaN,normal,NaN
freq,NaN,NaN,NaN,NaN,988,NaN
mean,499.500000,20.161158,0.510625,2.012499,NaN,10.416923
std,288.819436,3.551832,0.149618,0.231031,NaN,5.533852
min,0.000000,13.056041,0.058942,1.446479,NaN,1.000677
25%,249.750000,16.763544,0.409064,1.816269,NaN,5.670154
50%,499.500000,20.458939,0.509462,2.024081,NaN,10.295870
75%,749.250000,23.433047,0.609332,2.208529,NaN,15.212482
max,999.000000,26.537331,0.978966,2.569301,NaN,19.984625

## Parte 5 — Comprensión de listas

Use comprensión de listas para obtener:

1. Lista de potencias válidas.
2. Lista de temperaturas válidas.
3. Lista de motores en alerta.

In [ ]:

potencias_validas = [
    calcular_potencia(row['voltaje'], row['current_A'])
    for index, row in registros_limpios.iterrows()
    if calcular_potencia(row['voltaje'], row['current_A']) is not None
]

temperaturas_validas = [
    temp for temp in registros_limpios['temperature_C'].dropna()
]

registros_limpios['estado_temperatura'] = [
    clasificar_temperatura(temp) for temp in registros_limpios['temperature_C']
]

motores_alerta = [
    row['time']
    for index, row in registros_limpios.iterrows()
    if row['estado_temperatura'] == 'Alerta'
]

pd.Series(potencias_validas).to_csv('potencias_validas.csv', index=False, header=False)
pd.Series(temperaturas_validas).to_csv('temperaturas_validas.csv', index=False, header=False)
pd.Series(motores_alerta).to_csv('motores_alerta.csv', index=False, header=False)

pot_val=pd.read_csv('/content/potencias_validas.csv')
display(pot_val.head())
display(pd.read_csv('temperaturas_validas.csv').head())
pd.read_csv('motores_alerta.csv').head()

print(potencias_validas[:5])

   16.217102131331227
0           37.606406
1           29.963295
2           28.188215
3           13.973571
4            7.898292

   20.397371322408983
0           19.989382
1           20.718098
2           21.518244
3           20.212251
4           20.311858

[16.217102131331227, 37.60640614913012, 29.963295215747642, 28.18821453289737, 13.973570742447468]

## Parte 6 — Comprensión de diccionarios

Cree un diccionario llamado `estado_por_motor` donde:

- La clave sea el `id` del motor.
- El valor sea el `estado_temperatura`.

In [ ]:
# TODO: cree el diccionario estado_por_motor

estado_por_motor = {
    row['time']: row['estado_temperatura']
    for index, row in registros_limpios.iterrows()
}

print(estado_por_motor)

{0.0: 'Precaucion', 1.0: 'Precaucion', 2.0: 'Precaucion', 3.0: 'Precaucion', 4.0: 'Precaucion', 5.0: 'Precaucion', 6.0: 'Precaucion', 7.0: 'Precaucion', 8.0: 'Precaucion', 9.0: 'Precaucion', 10.0: 'Precaucion', 11.0: 'Precaucion', 12.0: 'Precaucion', 13.0: 'Precaucion', 14.0: 'Precaucion', 15.0: 'Precaucion', 16.0: 'Precaucion', 17.0: 'Precaucion', 18.0: 'Precaucion', 19.0: 'Precaucion', 20.0: 'Precaucion', 21.0: 'Precaucion', 22.0: 'Precaucion', 23.0: 'Precaucion', 24.0: 'Precaucion', 25.0: 'Precaucion', 26.0: 'Precaucion', 27.0: 'Precaucion', 28.0: 'Precaucion', 29.0: 'Precaucion', 30.0: 'Precaucion', 31.0: 'Alerta', 32.0: 'Precaucion', 33.0: 'Precaucion', 34.0: 'Precaucion', 35.0: 'Precaucion', 36.0: 'Precaucion', 37.0: 'Precaucion', 38.0: 'Precaucion', 39.0: 'Precaucion', 40.0: 'Alerta', 41.0: 'Precaucion', 42.0: 'Precaucion', 43.0: 'Precaucion', 44.0: 'Precaucion', 45.0: 'Precaucion', 46.0: 'Precaucion', 47.0: 'Alerta', 48.0: 'Alerta', 49.0: 'Precaucion', 50.0: 'Alerta', 51.0: 'Precaucion', 52.0: 'Precaucion', 53.0: 'Alerta', 54.0: 'Alerta', 55.0: 'Alerta', 56.0: 'Precaucion', 57.0: 'Alerta', 58.0: 'Alerta', 59.0: 'Alerta', 60.0: 'Alerta', 61.0: 'Alerta', 62.0: 'Precaucion', 63.0: 'Precaucion', 64.0: 'Alerta', 65.0: 'Alerta', 66.0: 'Alerta', 67.0: 'Alerta', 68.0: 'Alerta', 69.0: 'Alerta', 70.0: 'Alerta', 71.0: 'Alerta', 72.0: 'Alerta', 73.0: 'Alerta', 74.0: 'Precaucion', 75.0: 'Alerta', 76.0: 'Alerta', 77.0: 'Alerta', 78.0: 'Alerta', 79.0: 'Precaucion', 80.0: 'Alerta', 81.0: 'Alerta', 82.0: 'Alerta', 83.0: 'Alerta', 84.0: 'Alerta', 85.0: 'Alerta', 86.0: 'Alerta', 87.0: 'Alerta', 88.0: 'Alerta', 89.0: 'Alerta', 90.0: 'Alerta', 91.0: 'Alerta', 92.0: 'Alerta', 93.0: 'Alerta', 94.0: 'Alerta', 95.0: 'Precaucion', 96.0: 'Alerta', 97.0: 'Alerta', 98.0: 'Alerta', 99.0: 'Alerta', 100.0: 'Precaucion', 101.0: 'Alerta', 102.0: 'Alerta', 103.0: 'Precaucion', 104.0: 'Alerta', 105.0: 'Alerta', 106.0: 'Alerta', 107.0: 'Alerta', 108.0: 'Alerta', 109.0: 'Alerta', 110.0: 'Precaucion', 111.0: 'Precaucion', 112.0: 'Precaucion', 113.0: 'Alerta', 114.0: 'Precaucion', 115.0: 'Precaucion', 116.0: 'Precaucion', 117.0: 'Precaucion', 118.0: 'Alerta', 119.0: 'Alerta', 120.0: 'Alerta', 121.0: 'Precaucion', 122.0: 'Alerta', 123.0: 'Precaucion', 124.0: 'Precaucion', 125.0: 'Alerta', 126.0: 'Precaucion', 127.0: 'Precaucion', 128.0: 'Precaucion', 129.0: 'Precaucion', 130.0: 'Precaucion', 131.0: 'Precaucion', 132.0: 'Precaucion', 133.0: 'Precaucion', 134.0: 'Precaucion', 135.0: 'Precaucion', 136.0: 'Precaucion', 137.0: 'Precaucion', 138.0: 'Precaucion', 139.0: 'Precaucion', 140.0: 'Precaucion', 141.0: 'Precaucion', 142.0: 'Precaucion', 143.0: 'Precaucion', 144.0: 'Precaucion', 145.0: 'Precaucion', 146.0: 'Precaucion', 147.0: 'Precaucion', 148.0: 'Precaucion', 149.0: 'Precaucion', 150.0: 'Precaucion', 151.0: 'Precaucion', 152.0: 'Precaucion', 153.0: 'Precaucion', 154.0: 'Precaucion', 155.0: 'Precaucion', 156.0: 'Precaucion', 157.0: 'Precaucion', 158.0: 'Precaucion', 159.0: 'Precaucion', 160.0: 'Precaucion', 161.0: 'Precaucion', 162.0: 'Precaucion', 163.0: 'Precaucion', 164.0: 'Precaucion', 165.0: 'Precaucion', 166.0: 'Precaucion', 167.0: 'Precaucion', 168.0: 'Precaucion', 169.0: 'Precaucion', 170.0: 'Precaucion', 171.0: 'Precaucion', 172.0: 'Precaucion', 173.0: 'Precaucion', 174.0: 'Precaucion', 175.0: 'Precaucion', 176.0: 'Precaucion', 177.0: 'Precaucion', 178.0: 'Precaucion', 179.0: 'Precaucion', 180.0: 'Precaucion', 181.0: 'Precaucion', 182.0: 'Precaucion', 183.0: 'Precaucion', 184.0: 'Precaucion', 185.0: 'Precaucion', 186.0: 'Precaucion', 187.0: 'Precaucion', 188.0: 'Precaucion', 189.0: 'Precaucion', 190.0: 'Precaucion', 191.0: 'Precaucion', 192.0: 'Precaucion', 193.0: 'Precaucion', 194.0: 'Precaucion', 195.0: 'Precaucion', 196.0: 'Precaucion', 197.0: 'Precaucion', 198.0: 'Precaucion', 199.0: 'Precaucion', 200.0: 'Precaucion', 201.0: 'Precaucion', 202.0: 'Precaucion', 203.0: 'Precaucion', 204.0: 'Normal', 205.0: 'Precaucion', 206.0: 'Precaucion', 207.0: 'Precaucion', 208.0: 'Precaucion', 209.0: 'Precaucion', 210.0: 'Precaucion', 211.0: 'Precaucion', 212.0: 'Precaucion', 213.0: 'Precaucion', 214.0: 'Precaucion', 215.0: 'Precaucion', 216.0: 'Normal', 217.0: 'Precaucion', 218.0: 'Normal', 219.0: 'Precaucion', 220.0: 'Precaucion', 221.0: 'Normal', 222.0: 'Precaucion', 223.0: 'Normal', 224.0: 'Normal', 225.0: 'Precaucion', 226.0: 'Precaucion', 227.0: 'Normal', 228.0: 'Normal', 229.0: 'Precaucion', 230.0: 'Normal', 231.0: 'Precaucion', 232.0: 'Precaucion', 233.0: 'Normal', 234.0: 'Precaucion', 235.0: 'Precaucion', 236.0: 'Normal', 237.0: 'Precaucion', 238.0: 'Normal', 239.0: 'Precaucion', 240.0: 'Normal', 241.0: 'Normal', 242.0: 'Precaucion', 243.0: 'Precaucion', 244.0: 'Normal', 245.0: 'Normal', 246.0: 'Normal', 247.0: 'Normal', 248.0: 'Precaucion', 249.0: 'Precaucion', 250.0: 'Normal', 251.0: 'Precaucion', 252.0: 'Precaucion', 253.0: 'Precaucion', 254.0: 'Normal', 255.0: 'Normal', 256.0: 'Precaucion', 257.0: 'Normal', 258.0: 'Precaucion', 259.0: 'Precaucion', 260.0: 'Normal', 261.0: 'Precaucion', 262.0: 'Normal', 263.0: 'Normal', 264.0: 'Precaucion', 265.0: 'Normal', 266.0: 'Precaucion', 267.0: 'Normal', 268.0: 'Precaucion', 269.0: 'Precaucion', 270.0: 'Precaucion', 271.0: 'Precaucion', 272.0: 'Precaucion', 273.0: 'Precaucion', 274.0: 'Precaucion', 275.0: 'Precaucion', 276.0: 'Precaucion', 277.0: 'Precaucion', 278.0: 'Precaucion', 279.0: 'Precaucion', 280.0: 'Precaucion', 281.0: 'Precaucion', 282.0: 'Precaucion', 283.0: 'Precaucion', 284.0: 'Precaucion', 285.0: 'Precaucion', 286.0: 'Precaucion', 287.0: 'Precaucion', 288.0: 'Precaucion', 289.0: 'Precaucion', 290.0: 'Precaucion', 291.0: 'Precaucion', 292.0: 'Precaucion', 293.0: 'Precaucion', 294.0: 'Precaucion', 295.0: 'Precaucion', 296.0: 'Precaucion', 297.0: 'Precaucion', 298.0: 'Precaucion', 299.0: 'Precaucion', 300.0: 'Precaucion', 301.0: 'Precaucion', 302.0: 'Precaucion', 303.0: 'Precaucion', 304.0: 'Precaucion', 305.0: 'Precaucion', 306.0: 'Precaucion', 307.0: 'Precaucion', 308.0: 'Precaucion', 309.0: 'Precaucion', 310.0: 'Precaucion', 311.0: 'Precaucion', 312.0: 'Precaucion', 313.0: 'Precaucion', 314.0: 'Precaucion', 315.0: 'Precaucion', 316.0: 'Precaucion', 317.0: 'Precaucion', 318.0: 'Precaucion', 319.0: 'Precaucion', 320.0: 'Precaucion', 321.0: 'Precaucion', 322.0: 'Precaucion', 323.0: 'Precaucion', 324.0: 'Precaucion', 325.0: 'Precaucion', 326.0: 'Precaucion', 327.0: 'Precaucion', 328.0: 'Precaucion', 329.0: 'Precaucion', 330.0: 'Precaucion', 331.0: 'Precaucion', 332.0: 'Precaucion', 333.0: 'Precaucion', 334.0: 'Precaucion', 335.0: 'Precaucion', 336.0: 'Precaucion', 337.0: 'Precaucion', 338.0: 'Precaucion', 339.0: 'Precaucion', 340.0: 'Precaucion', 341.0: 'Precaucion', 342.0: 'Precaucion', 343.0: 'Precaucion', 344.0: 'Precaucion', 345.0: 'Precaucion', 346.0: 'Precaucion', 347.0: 'Precaucion', 348.0: 'Precaucion', 349.0: 'Precaucion', 350.0: 'Precaucion', 351.0: 'Alerta', 352.0: 'Alerta', 353.0: 'Precaucion', 354.0: 'Precaucion', 355.0: 'Precaucion', 356.0: 'Precaucion', 357.0: 'Precaucion', 358.0: 'Alerta', 359.0: 'Precaucion', 360.0: 'Alerta', 361.0: 'Alerta', 362.0: 'Precaucion', 363.0: 'Alerta', 364.0: 'Alerta', 365.0: 'Precaucion', 366.0: 'Alerta', 367.0: 'Alerta', 368.0: 'Alerta', 369.0: 'Precaucion', 370.0: 'Alerta', 371.0: 'Alerta', 372.0: 'Alerta', 373.0: 'Alerta', 374.0: 'Alerta', 375.0: 'Alerta', 376.0: 'Alerta', 377.0: 'Alerta', 378.0: 'Alerta', 379.0: 'Alerta', 380.0: 'Alerta', 381.0: 'Alerta', 382.0: 'Precaucion', 383.0: 'Alerta', 384.0: 'Alerta', 385.0: 'Alerta', 386.0: 'Alerta', 387.0: 'Alerta', 388.0: 'Alerta', 389.0: 'Alerta', 390.0: 'Alerta', 391.0: 'Alerta', 392.0: 'Precaucion', 393.0: 'Alerta', 394.0: 'Alerta', 395.0: 'Alerta', 396.0: 'Precaucion', 397.0: 'Alerta', 398.0: 'Alerta', 399.0: 'Alerta', 400.0: 'Precaucion', 401.0: 'Alerta', 402.0: 'Alerta', 403.0: 'Alerta', 404.0: 'Alerta', 405.0: 'Alerta', 406.0: 'Precaucion', 407.0: 'Alerta', 408.0: 'Alerta', 409.0: 'Alerta', 410.0: 'Alerta', 411.0: 'Precaucion', 412.0: 'Precaucion', 413.0: 'Alerta', 414.0: 'Alerta', 415.0: 'Precaucion', 416.0: 'Alerta', 417.0: 'Alerta', 418.0: 'Alerta', 419.0: 'Alerta', 420.0: 'Alerta', 421.0: 'Alerta', 422.0: 'Precaucion', 423.0: 'Alerta', 424.0: 'Alerta', 425.0: 'Alerta', 426.0: 'Precaucion', 427.0: 'Alerta', 428.0: 'Alerta', 429.0: 'Precaucion', 430.0: 'Precaucion', 431.0: 'Precaucion', 432.0: 'Precaucion', 433.0: 'Alerta', 434.0: 'Alerta', 435.0: 'Precaucion', 436.0: 'Alerta', 437.0: 'Precaucion', 438.0: 'Precaucion', 439.0: 'Precaucion', 440.0: 'Precaucion', 441.0: 'Precaucion', 442.0: 'Precaucion', 443.0: 'Precaucion', 444.0: 'Precaucion', 445.0: 'Precaucion', 446.0: 'Precaucion', 447.0: 'Precaucion', 448.0: 'Precaucion', 449.0: 'Precaucion', 450.0: 'Precaucion', 451.0: 'Precaucion', 452.0: 'Precaucion', 453.0: 'Precaucion', 454.0: 'Precaucion', 455.0: 'Precaucion', 456.0: 'Precaucion', 457.0: 'Precaucion', 458.0: 'Precaucion', 459.0: 'Precaucion', 460.0: 'Precaucion', 461.0: 'Precaucion', 462.0: 'Precaucion', 463.0: 'Precaucion', 464.0: 'Precaucion', 465.0: 'Precaucion', 466.0: 'Precaucion', 467.0: 'Precaucion', 468.0: 'Precaucion', 469.0: 'Precaucion', 470.0: 'Precaucion', 471.0: 'Precaucion', 472.0: 'Precaucion', 473.0: 'Precaucion', 474.0: 'Precaucion', 475.0: 'Precaucion', 476.0: 'Precaucion', 477.0: 'Precaucion', 478.0: 'Precaucion', 479.0: 'Precaucion', 480.0: 'Precaucion', 481.0: 'Precaucion', 482.0: 'Precaucion', 483.0: 'Precaucion', 484.0: 'Precaucion', 485.0: 'Precaucion', 486.0: 'Precaucion', 487.0: 'Precaucion', 488.0: 'Precaucion', 489.0: 'Precaucion', 490.0: 'Precaucion', 491.0: 'Precaucion', 492.0: 'Precaucion', 493.0: 'Precaucion', 494.0: 'Precaucion', 495.0: 'Precaucion', 496.0: 'Precaucion', 497.0: 'Precaucion', 498.0: 'Precaucion', 499.0: 'Precaucion', 500.0: 'Precaucion', 501.0: 'Precaucion', 502.0: 'Precaucion', 503.0: 'Precaucion', 504.0: 'Precaucion', 505.0: 'Precaucion', 506.0: 'Precaucion', 507.0: 'Precaucion', 508.0: 'Precaucion', 509.0: 'Precaucion', 510.0: 'Precaucion', 511.0: 'Precaucion', 512.0: 'Precaucion', 513.0: 'Precaucion', 514.0: 'Precaucion', 515.0: 'Precaucion', 516.0: 'Precaucion', 517.0: 'Precaucion', 518.0: 'Precaucion', 519.0: 'Precaucion', 520.0: 'Normal', 521.0: 'Precaucion', 522.0: 'Precaucion', 523.0: 'Precaucion', 524.0: 'Precaucion', 525.0: 'Normal', 526.0: 'Normal', 527.0: 'Precaucion', 528.0: 'Precaucion', 529.0: 'Normal', 530.0: 'Precaucion', 531.0: 'Normal', 532.0: 'Precaucion', 533.0: 'Normal', 534.0: 'Normal', 535.0: 'Precaucion', 536.0: 'Normal', 537.0: 'Normal', 538.0: 'Precaucion', 539.0: 'Normal', 540.0: 'Precaucion', 541.0: 'Normal', 542.0: 'Precaucion', 543.0: 'Precaucion', 544.0: 'Normal', 545.0: 'Normal', 546.0: 'Precaucion', 547.0: 'Normal', 548.0: 'Precaucion', 549.0: 'Normal', 550.0: 'Precaucion', 551.0: 'Normal', 552.0: 'Precaucion', 553.0: 'Precaucion', 554.0: 'Precaucion', 555.0: 'Normal', 556.0: 'Normal', 557.0: 'Normal', 558.0: 'Precaucion', 559.0: 'Normal', 560.0: 'Precaucion', 561.0: 'Precaucion', 562.0: 'Precaucion', 563.0: 'Normal', 564.0: 'Precaucion', 565.0: 'Normal', 566.0: 'Normal', 567.0: 'Normal', 568.0: 'Normal', 569.0: 'Precaucion', 570.0: 'Precaucion', 571.0: 'Precaucion', 572.0: 'Precaucion', 573.0: 'Precaucion', 574.0: 'Precaucion', 575.0: 'Normal', 576.0: 'Precaucion', 577.0: 'Precaucion', 578.0: 'Normal', 579.0: 'Precaucion', 580.0: 'Precaucion', 581.0: 'Precaucion', 582.0: 'Precaucion', 583.0: 'Precaucion', 584.0: 'Precaucion', 585.0: 'Precaucion', 586.0: 'Precaucion', 587.0: 'Precaucion', 588.0: 'Precaucion', 589.0: 'Precaucion', 590.0: 'Precaucion', 591.0: 'Precaucion', 592.0: 'Precaucion', 593.0: 'Precaucion', 594.0: 'Precaucion', 595.0: 'Precaucion', 596.0: 'Precaucion', 597.0: 'Precaucion', 598.0: 'Precaucion', 599.0: 'Precaucion', 600.0: 'Precaucion', 601.0: 'Precaucion', 602.0: 'Precaucion', 603.0: 'Precaucion', 604.0: 'Precaucion', 605.0: 'Precaucion', 606.0: 'Precaucion', 607.0: 'Precaucion', 608.0: 'Precaucion', 609.0: 'Precaucion', 610.0: 'Precaucion', 611.0: 'Precaucion', 612.0: 'Precaucion', 613.0: 'Precaucion', 614.0: 'Precaucion', 615.0: 'Precaucion', 616.0: 'Precaucion', 617.0: 'Precaucion', 618.0: 'Precaucion', 619.0: 'Precaucion', 620.0: 'Precaucion', 621.0: 'Precaucion', 622.0: 'Precaucion', 623.0: 'Precaucion', 624.0: 'Precaucion', 625.0: 'Precaucion', 626.0: 'Precaucion', 627.0: 'Precaucion', 628.0: 'Precaucion', 629.0: 'Precaucion', 630.0: 'Precaucion', 631.0: 'Precaucion', 632.0: 'Precaucion', 633.0: 'Precaucion', 634.0: 'Precaucion', 635.0: 'Precaucion', 636.0: 'Precaucion', 637.0: 'Precaucion', 638.0: 'Precaucion', 639.0: 'Precaucion', 640.0: 'Precaucion', 641.0: 'Precaucion', 642.0: 'Precaucion', 643.0: 'Precaucion', 644.0: 'Precaucion', 645.0: 'Precaucion', 646.0: 'Precaucion', 647.0: 'Precaucion', 648.0: 'Precaucion', 649.0: 'Precaucion', 650.0: 'Precaucion', 651.0: 'Precaucion', 652.0: 'Precaucion', 653.0: 'Precaucion', 654.0: 'Alerta', 655.0: 'Precaucion', 656.0: 'Precaucion', 657.0: 'Precaucion', 658.0: 'Precaucion', 659.0: 'Precaucion', 660.0: 'Precaucion', 661.0: 'Precaucion', 662.0: 'Precaucion', 663.0: 'Precaucion', 664.0: 'Precaucion', 665.0: 'Precaucion', 666.0: 'Precaucion', 667.0: 'Alerta', 668.0: 'Precaucion', 669.0: 'Alerta', 670.0: 'Alerta', 671.0: 'Precaucion', 672.0: 'Precaucion', 673.0: 'Precaucion', 674.0: 'Precaucion', 675.0: 'Precaucion', 676.0: 'Precaucion', 677.0: 'Alerta', 678.0: 'Alerta', 679.0: 'Alerta', 680.0: 'Alerta', 681.0: 'Precaucion', 682.0: 'Precaucion', 683.0: 'Alerta', 684.0: 'Precaucion', 685.0: 'Alerta', 686.0: 'Alerta', 687.0: 'Alerta', 688.0: 'Alerta', 689.0: 'Alerta', 690.0: 'Alerta', 691.0: 'Alerta', 692.0: 'Precaucion', 693.0: 'Alerta', 694.0: 'Alerta', 695.0: 'Alerta', 696.0: 'Alerta', 697.0: 'Precaucion', 698.0: 'Alerta', 699.0: 'Alerta', 700.0: 'Alerta', 701.0: 'Alerta', 702.0: 'Alerta', 703.0: 'Precaucion', 704.0: 'Precaucion', 705.0: 'Alerta', 706.0: 'Precaucion', 707.0: 'Alerta', 708.0: 'Precaucion', 709.0: 'Alerta', 710.0: 'Alerta', 711.0: 'Alerta', 712.0: 'Alerta', 713.0: 'Alerta', 714.0: 'Alerta', 715.0: 'Alerta', 716.0: 'Alerta', 717.0: 'Alerta', 718.0: 'Alerta', 719.0: 'Alerta', 720.0: 'Alerta', 721.0: 'Precaucion', 722.0: 'Precaucion', 723.0: 'Alerta', 724.0: 'Alerta', 725.0: 'Alerta', 726.0: 'Alerta', 727.0: 'Alerta', 728.0: 'Alerta', 729.0: 'Precaucion', 730.0: 'Alerta', 731.0: 'Precaucion', 732.0: 'Alerta', 733.0: 'Precaucion', 734.0: 'Alerta', 735.0: 'Alerta', 736.0: 'Alerta', 737.0: 'Alerta', 738.0: 'Alerta', 739.0: 'Alerta', 740.0: 'Precaucion', 741.0: 'Precaucion', 742.0: 'Precaucion', 743.0: 'Precaucion', 744.0: 'Alerta', 745.0: 'Precaucion', 746.0: 'Precaucion', 747.0: 'Precaucion', 748.0: 'Precaucion', 749.0: 'Precaucion', 750.0: 'Precaucion', 751.0: 'Precaucion', 752.0: 'Precaucion', 753.0: 'Precaucion', 754.0: 'Precaucion', 755.0: 'Alerta', 756.0: 'Precaucion', 757.0: 'Precaucion', 758.0: 'Precaucion', 759.0: 'Precaucion', 760.0: 'Precaucion', 761.0: 'Precaucion', 762.0: 'Alerta', 763.0: 'Precaucion', 764.0: 'Precaucion', 765.0: 'Precaucion', 766.0: 'Precaucion', 767.0: 'Precaucion', 768.0: 'Precaucion', 769.0: 'Precaucion', 770.0: 'Precaucion', 771.0: 'Precaucion', 772.0: 'Precaucion', 773.0: 'Precaucion', 774.0: 'Precaucion', 775.0: 'Precaucion', 776.0: 'Precaucion', 777.0: 'Precaucion', 778.0: 'Precaucion', 779.0: 'Precaucion', 780.0: 'Precaucion', 781.0: 'Precaucion', 782.0: 'Precaucion', 783.0: 'Precaucion', 784.0: 'Precaucion', 785.0: 'Precaucion', 786.0: 'Precaucion', 787.0: 'Precaucion', 788.0: 'Precaucion', 789.0: 'Precaucion', 790.0: 'Precaucion', 791.0: 'Precaucion', 792.0: 'Precaucion', 793.0: 'Precaucion', 794.0: 'Precaucion', 795.0: 'Precaucion', 796.0: 'Precaucion', 797.0: 'Precaucion', 798.0: 'Precaucion', 799.0: 'Precaucion', 800.0: 'Precaucion', 801.0: 'Precaucion', 802.0: 'Precaucion', 803.0: 'Precaucion', 804.0: 'Precaucion', 805.0: 'Precaucion', 806.0: 'Precaucion', 807.0: 'Precaucion', 808.0: 'Precaucion', 809.0: 'Precaucion', 810.0: 'Precaucion', 811.0: 'Precaucion', 812.0: 'Precaucion', 813.0: 'Precaucion', 814.0: 'Precaucion', 815.0: 'Precaucion', 816.0: 'Precaucion', 817.0: 'Precaucion', 818.0: 'Precaucion', 819.0: 'Precaucion', 820.0: 'Precaucion', 821.0: 'Precaucion', 822.0: 'Precaucion', 823.0: 'Precaucion', 824.0: 'Precaucion', 825.0: 'Precaucion', 826.0: 'Precaucion', 827.0: 'Precaucion', 828.0: 'Precaucion', 829.0: 'Precaucion', 830.0: 'Precaucion', 831.0: 'Precaucion', 832.0: 'Precaucion', 833.0: 'Precaucion', 834.0: 'Precaucion', 835.0: 'Precaucion', 836.0: 'Precaucion', 837.0: 'Normal', 838.0: 'Precaucion', 839.0: 'Precaucion', 840.0: 'Precaucion', 841.0: 'Precaucion', 842.0: 'Normal', 843.0: 'Precaucion', 844.0: 'Precaucion', 845.0: 'Precaucion', 846.0: 'Precaucion', 847.0: 'Precaucion', 848.0: 'Normal', 849.0: 'Normal', 850.0: 'Normal', 851.0: 'Normal', 852.0: 'Normal', 853.0: 'Precaucion', 854.0: 'Precaucion', 855.0: 'Normal', 856.0: 'Normal', 857.0: 'Precaucion', 858.0: 'Normal', 859.0: 'Precaucion', 860.0: 'Precaucion', 861.0: 'Normal', 862.0: 'Precaucion', 863.0: 'Precaucion', 864.0: 'Normal', 865.0: 'Normal', 866.0: 'Precaucion', 867.0: 'Precaucion', 868.0: 'Precaucion', 869.0: 'Precaucion', 870.0: 'Normal', 871.0: 'Normal', 872.0: 'Normal', 873.0: 'Normal', 874.0: 'Precaucion', 875.0: 'Precaucion', 876.0: 'Normal', 877.0: 'Precaucion', 878.0: 'Precaucion', 879.0: 'Precaucion', 880.0: 'Precaucion', 881.0: 'Normal', 882.0: 'Normal', 883.0: 'Precaucion', 884.0: 'Precaucion', 885.0: 'Precaucion', 886.0: 'Precaucion', 887.0: 'Precaucion', 888.0: 'Precaucion', 889.0: 'Precaucion', 890.0: 'Precaucion', 891.0: 'Precaucion', 892.0: 'Precaucion', 893.0: 'Precaucion', 894.0: 'Precaucion', 895.0: 'Precaucion', 896.0: 'Precaucion', 897.0: 'Precaucion', 898.0: 'Precaucion', 899.0: 'Precaucion', 900.0: 'Precaucion', 901.0: 'Precaucion', 902.0: 'Precaucion', 903.0: 'Precaucion', 904.0: 'Precaucion', 905.0: 'Precaucion', 906.0: 'Precaucion', 907.0: 'Precaucion', 908.0: 'Precaucion', 909.0: 'Precaucion', 910.0: 'Precaucion', 911.0: 'Precaucion', 912.0: 'Precaucion', 913.0: 'Precaucion', 914.0: 'Precaucion', 915.0: 'Precaucion', 916.0: 'Precaucion', 917.0: 'Precaucion', 918.0: 'Precaucion', 919.0: 'Precaucion', 920.0: 'Precaucion', 921.0: 'Precaucion', 922.0: 'Precaucion', 923.0: 'Precaucion', 924.0: 'Precaucion', 925.0: 'Precaucion', 926.0: 'Precaucion', 927.0: 'Precaucion', 928.0: 'Precaucion', 929.0: 'Precaucion', 930.0: 'Precaucion', 931.0: 'Precaucion', 932.0: 'Precaucion', 933.0: 'Precaucion', 934.0: 'Precaucion', 935.0: 'Precaucion', 936.0: 'Precaucion', 937.0: 'Precaucion', 938.0: 'Precaucion', 939.0: 'Precaucion', 940.0: 'Precaucion', 941.0: 'Precaucion', 942.0: 'Precaucion', 943.0: 'Precaucion', 944.0: 'Precaucion', 945.0: 'Precaucion', 946.0: 'Precaucion', 947.0: 'Precaucion', 948.0: 'Precaucion', 949.0: 'Precaucion', 950.0: 'Precaucion', 951.0: 'Precaucion', 952.0: 'Precaucion', 953.0: 'Precaucion', 954.0: 'Precaucion', 955.0: 'Precaucion', 956.0: 'Precaucion', 957.0: 'Precaucion', 958.0: 'Precaucion', 959.0: 'Precaucion', 960.0: 'Precaucion', 961.0: 'Precaucion', 962.0: 'Precaucion', 963.0: 'Precaucion', 964.0: 'Precaucion', 965.0: 'Precaucion', 966.0: 'Precaucion', 967.0: 'Precaucion', 968.0: 'Precaucion', 969.0: 'Precaucion', 970.0: 'Precaucion', 971.0: 'Precaucion', 972.0: 'Precaucion', 973.0: 'Precaucion', 974.0: 'Precaucion', 975.0: 'Precaucion', 976.0: 'Precaucion', 977.0: 'Precaucion', 978.0: 'Precaucion', 979.0: 'Precaucion', 980.0: 'Alerta', 981.0: 'Precaucion', 982.0: 'Precaucion', 983.0: 'Precaucion', 984.0: 'Precaucion', 985.0: 'Precaucion', 986.0: 'Alerta', 987.0: 'Alerta', 988.0: 'Precaucion', 989.0: 'Alerta', 990.0: 'Alerta', 991.0: 'Precaucion', 992.0: 'Precaucion', 993.0: 'Precaucion', 994.0: 'Precaucion', 995.0: 'Alerta', 996.0: 'Alerta', 997.0: 'Alerta', 998.0: 'Alerta', 999.0: 'Alerta'}

## Parte 7 — Resumen automático

Cree una función llamada `generar_resumen(registros)` que retorne un diccionario con:

- `total_registros`
- `registros_validos_potencia`
- `potencia_promedio`
- `temperatura_promedio`
- `cantidad_alertas`
- `cantidad_precauciones`
- `cantidad_normales`

In [ ]:
registros_limpios['potencia_W'] = registros_limpios.apply(
    lambda row: calcular_potencia(row['voltaje'], row['current_A']),
    axis=1
)

display(registros_limpios.head())

,time,temperature_C,vibration_g,current_A,system_state,voltaje,estado_temperatura,potencia_W
0,0.0,20.397371,0.709903,1.932482,normal,8.391851,Precaucion,16.217102
1,1.0,19.989382,0.638695,1.995546,normal,18.845169,Precaucion,37.606406
2,2.0,20.718098,0.508945,1.940743,normal,15.439083,Precaucion,29.963295
3,3.0,21.518244,0.402959,1.999154,normal,14.100072,Precaucion,28.188215
4,4.0,20.212251,0.604733,1.850520,normal,7.551159,Precaucion,13.973571

In [ ]:
# TODO: cree la función generar_resumen


def generar_resumen(registros):
  resumen={
      len(registros),
      len([potencia for potencia in registros['potencia_W'] if potencia is not None]),


  }




resumen = generar_resumen(registros_limpios)
resumen

## Parte 8 — Visualización como tabla

Convierta `registros_limpios` en un `DataFrame` de Pandas.

In [ ]:
import pandas as pd

# TODO: cree un DataFrame llamado df
df = pd.DataFrame(registros_limpios)

## Parte 9 — Buenas prácticas

Revise su notebook y verifique:

- Los nombres de variables son claros.
- Las funciones tienen una tarea específica.
- El código no está repetido innecesariamente.
- Las celdas están ejecutadas en orden.
- Hay explicaciones en texto.

## Parte 10 — Repositorio inicial en GitHub

Cree un repositorio en GitHub con el nombre:

**analisis-datos-python-apellido-nombre**

Estructura mínima esperada:

```text
analisis-datos-python-apellido-nombre/
│
├── README.md
├── requirements.txt
├── notebooks/
│   ├── semana_02_introduccion.ipynb
│   ├── semana_03_fundamentos_python.ipynb
│   └── semana_04_funciones_modularizacion.ipynb
│
├── data/
│   ├── raw/
│   └── processed/
│
├── src/
│   └── funciones.py
│
└── reports/
    └── figuras/
```

Enlace al repositorio:

Pegue aquí el enlace de su repositorio.

**Enlace al repositorio:**  
https://github.com/Julian12005/analisis-datos-python_jimenez_lara

## Parte 11 — Reflexión final

Responda:

1. ¿Qué ventaja tuvo usar funciones en el procesamiento de los registros?
2. ¿Por qué es importante manejar errores antes de analizar datos?
3. ¿Qué función del taller considera más útil?
4. ¿Qué elemento del repositorio ayuda más a la reproducibilidad?

**Respuesta:**

1.  **¿Qué ventaja tuvo usar funciones en el procesamiento de los registros?**
    Usar funciones permitió modularizar el código, haciendo que cada tarea (convertir a float, calcular potencia, clasificar temperatura) fuera independiente y reutilizable. Esto mejora la legibilidad, facilita la depuración y permite cambios en la lógica de negocio sin afectar otras partes del código.

2.  **¿Por qué es importante manejar errores antes de analizar datos?**
    Porque permite identificar y aislar valores inválidos, prevenir interrupciones inesperadas en el procesamiento y asegurar que los análisis posteriores se realicen sobre datos confiables, evitando resultados erróneos o sesgados.

3.  **¿Qué función del taller considera más útil?**
    Considero que la función `convertir_a_float` es la más útil. Constantemente uno puee encontrar datos en formatos incorrectos o con valores que no son numéricos cuando deberían serlo. Esta función permite una limpieza fundamental de los datos, preparando las columnas para cálculos y análisis posteriores. Sin una correcta conversión de tipos, muchas otras operaciones serían imposibles o llevarían a errores.

4.  **¿Qué elemento del repositorio ayuda más a la reproducibilidad?**
    El archivo `requirements.txt` y la estructura de carpetas `data/raw/` y `data/processed/` son los elementos que más contribuyen a la reproducibilidad. El `requirements.txt` asegura que todos los colaboradores o usuarios tengan el mismo entorno de desarrollo con las mismas versiones de las librerías. Las carpetas `data/raw/` y `data/processed/` garantizan que los datos originales y los datos transformados estén organizados y sean accesibles, lo cual es esencial para seguir el flujo de trabajo y replicar los resultados.